defaults:
  - ../ppo_trainer@models.model_0.ppo_trainer_config: eval
  - ../ppo_trainer@models.model_1.ppo_trainer_config: eval
  - _self_

specialization: "full"
lora_rank: 16
lora_alpha: 32
resource:
  nnodes: 1
  n_gpus_per_node: 2
  trust_remote_code: true

env:
  name: code_env
  dataset: "code_contests"
  benchmark: "livecodebench"
  max_turns: 1
  resolve: false
  multi_modal: false
  batched_init: true

base_models:
  policy_0:
    path: "Qwen/Qwen2.5-Coder-1.5B-Instruct"
    name: "tests_generator_model"
  policy_1:
    path: "Qwen/Qwen2.5-Coder-1.5B-Instruct"
    name: "code_generator_model"

agent_policy_configs:
  num_agents: 2
  policy_list: ["example_generator_agent", "code_generator_agent"]
  agent_configs:
    agent_0:
      name: "example_generator_agent"
      policy_name: "tests_generator_model"
      enable_thinking: false
    agent_1:
      name: "code_generator_agent"
      policy_name: "code_generator_model"
      enable_thinking: false

multi_agent_interaction:
  turn_order: ["example_generator_agent", "code_generator_agent"]
  num_interacting_agents: 2

training:
  device: cuda
  total_training_steps: 200
  project_name: pettingllms
  experiment_name: code_1.5B_L3_full_model
  logger: [ 'console', 'wandb' ]
  model_checkpoints_dir: checkpoints
  ray_wait_register_center_timeout: 300
  train_batch_size: 4
  train_sample_num: 2
  validate_sample_num: 1
  sample_temperature: 1
  val_freq: 10
  resample_freq: 3
  epoch_size: 20
  max_prompt_length: 400
  max_response_length: 400
  lora_rank: ${lora_rank}
  lora_alpha: ${lora_alpha}

models:
  model_0:
    path: ${base_models.policy_0.path}
    name: ${base_models.policy_0.name}
    ppo_trainer_config:
      filter_method: mean
      filter_ratio: 0.5
      data: 
        max_prompt_length: ${training.max_prompt_length}
        max_response_length: ${training.max_response_length}
      actor_rollout_ref:
        model:
          path: ${base_models.policy_0.path}
        rollout:
          temperature: ${training.sample_temperature}
          prompt_length: ${training.max_prompt_length}
          response_length: ${training.max_response_length}
          tensor_model_parallel_size: 1
        trainer:
          n_gpus_per_node: 1
          n_training_gpus_per_node: 1
  model_1:
    path: ${base_models.policy_1.path}
    name: ${base_models.policy_1.name}
    ppo_trainer_config:
      filter_method: mean
      filter_ratio: 0.5
      data: 
        max_prompt_length: ${training.max_prompt_length}
        max_response_length: ${training.max_response_length}
      actor_rollout_ref:
        model:
          path: ${base_models.policy_1.path}
        rollout:
          temperature: ${training.sample_temperature}
          prompt_length: ${training.max_prompt_length}
          response_length: ${training.max_response_length}
          tensor_model_parallel_size: 1
        trainer:
          n_gpus_per_node: 1
          n_training_gpus_per_node: 1